### ISSUE TITLE
As a Product Owner I want that the Wsdlvalidator is not anymore checking the SOAP faults and Wsdlvalidator is also included to RHEL packaging so that it's usability is improved

### ISSUE THREAD

**Issue by hanhaka** [vrk-kpa/xroad-joint-development#147]
**Affected components**: Wsdlvalidator, packaging
**Affected documentation**: -
**Estimated delivery**: Q2/2017
**External reference**: https://jira.csc.fi/browse/PVAYLADEV-730

**Problem**
Wsdlvalidator checks for the some reason SOAP faults when importing the WSDL. It seems that the checkForSoapFault() is relict from X-Road v5 migration, where service mediator was developed. So it's safe to remove this function.

In practice when the WSDL is imported in the security server UI it logs an exception to jetty.log as follows:
2017-04-21 16:47:31,152 [qtp972765878-12] INFO  ee.ria.xroad.proxyui.WSDLParser - Exception while parsing: {}
ee.ria.xroad.common.CodedException: InvalidSoap: Malformed SOAP message: envelope missing
at ee.ria.xroad.common.message.SaxSoapParserImpl$XRoadSoapHandler.handleRootElement(SaxSoapParserImpl.java:368) ~[common-util-1.0.jar:na]
at ee.ria.xroad.common.message.SaxSoapParserImpl$XRoadSoapHandler.startElement(SaxSoapParserImpl.java:343) ~[common-util-1.0.jar:na]
at org.apache.xerces.parsers.AbstractSAXParser.startElement(AbstractSAXParser.java:498) ~[xercesImpl-2.11.0.SP5.jar:2.11.0.SP5]

Wsdlvalidator must be included also to RHEL packaging as it is already included to Ubuntu packaging.

**Acceptance criteria**
- Wsdlvalidator does not anymore check for the SOAP faults
- Wsdlvalidator is included to RHEL packaging
- RHEL packaging is tested to work ok in AWS development environment

**Comment by hanhaka** [comment]
Fixed in version 6.15.0
