### ISSUE TITLE
BUG: Security Server returns error message if SOAP Fault faultcode element uses namespace prefix other than SOAP-ENV

### ISSUE THREAD

**Issue by petkivim** [vrk-kpa/xroad-joint-development#38]
**Affected components**: xroad-common
**Affected documentation**: -
**Estimated delivery**: May 2016
**External reference**: https://jira.csc.fi/browse/PVAYLADEV-360

**Problem**

If service provider returns SOAP Fault that contains a namespace prefix other than `SOAP-ENV`, receives service consumer the error message below:

```
ee.ria.xroad.common.CodedException: ServiceFailed.MalformedSoap: UndeclaredPrefix: Cannot resolve 'soap:Server' as a QName: the prefix 'soap' is not declared.
```

Valid SOAP Fault returned by the service provider:

```
<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
   <soap:Body>
      <soap:Fault>
         <faultcode>soap:Server</faultcode>
         <faultstring>Fault occurred while processing.</faultstring>
      </soap:Fault>
   </soap:Body>
</soap:Envelope>
```

The message received by the service consumer:

```
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xroad="http://x-road.eu/xsd/xroad.xsd">
   <SOAP-ENV:Body>
      <SOAP-ENV:Fault>
         <faultcode>Server.ClientProxy.ServiceFailed.MalformedSoap</faultcode>
         <faultstring>UndeclaredPrefix: Cannot resolve 'soap:Server' as a QName: the prefix 'soap' is not declared.</faultstring>
         <faultactor/>
         <detail>
            <xroad:faultDetail>org.xml.sax.SAXParseException; UndeclaredPrefix: Cannot resolve 'soap:Server' as a QName: the prefix 'soap' is not declared.
    at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:203)
    at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.error(ErrorHandlerWrapper.java:134)
    at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:396)
    at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:327)
...
```

Security server recreates the SOAP Fault returned by the service provider using hard-coded strings. SOAP Envelope's namespace prefix is set to `SOAP-ENV`, but `faultcode` may use different prefix which causes the recreated message to be invalid.

See `SoapFault.createFaultXml()` for further [details](https://github.com/vrk-kpa/xroad-public/blob/master/src/common-util/src/main/java/ee/ria/xroad/common/message/SoapFault.java#L119).

**Acceptance criteria**
- Security Server uses the namespace prefix of the original SOAP Fault message returned by the service provider

**Comment by petkivim** [comment]
Fixed.
