### ISSUE TITLE
BUG: Large number of private keys causes Security Server to crash

### ISSUE THREAD

**Issue by petkivim** [vrk-kpa/xroad-joint-development#49]
**Affected components**: signer, jetty
**Affected documentation**: -
**Estimated delivery**: -
**External reference**: https://jira.csc.fi/browse/PVAYLADEV-406

**Problem**

Security Server stops responding if large number (> 200) of private keys have been generated, because requests to signer fail on timeout. Admin UI stops responding and the error below gets logged in Jetty's log.

```
2016-05-17 11:36:05,385 [qtp1211076369-14] INFO / - Failed to check software token status: HttpError: Connection to Signer (port 5558) timed out
2016-05-17 11:36:05,387 [qtp1211076369-14] INFO / - HttpError: Connection to Signer (port 5558) timed out
    at ee.ria.xroad.signer.protocol.SignerClient.connectionTimeoutException(ee/ria/xroad/signer/protocol/SignerClient.java:135)
    at ee.ria.xroad.signer.protocol.SignerClient.execute(ee/ria/xroad/signer/protocol/SignerClient.java:100)
    at ee.ria.xroad.commonui.SignerProxy.execute(ee/ria/xroad/commonui/SignerProxy.java:303)
    at ee.ria.xroad.commonui.SignerProxy.getTokens(ee/ria/xroad/commonui/SignerProxy.java:69)
    at java.lang.reflect.Method.invoke(java/lang/reflect/Method.java:498)
    at RUBY.software_token_initialized?(/var/tmp/xroad/jetty-proxy-ui-temp/webapp/WEB-INF/vendor/engines/common-ui/app/controllers/base_controller.rb:169)
    at RUBY.initialized?(/var/tmp/xroad/jetty-proxy-ui-temp/webapp/WEB-INF/app/controllers/application_controller.rb:204)
    at RUBY.check_conf(/var/tmp/xroad/jetty-proxy-ui-temp/webapp/WEB-INF/app/controllers/application_controller.rb:200)
    at RUBY._run__224140107__process_action__1989452405__callbacks(/var/tmp/xroad/jetty-proxy-ui-temp/webapp/WEB-INF/gems/gems/activesupport-3.2.22/lib/active_support/callbacks.rb:446)
    at RUBY._conditional_callback_around_99(/var/tmp/xroad/jetty-proxy-ui-temp/webapp/WEB-INF/gems/gems/activesupport-3.2.22/lib/active_support/callbacks.rb:225)
    at RUBY.transaction(/var/tmp/xroad/jetty-proxy-ui-temp/webapp/WEB-INF/app/controllers/application_controller.rb:155)
    at RUBY._conditional_callback_around_99(/var/tmp/xroad/jetty-proxy-ui-temp/webapp/WEB-INF/gems/gems/activesupport-3.2.22/lib/active_support/callbacks.rb:224)
    at RUBY._run__224140107__process_action__1989452405__callbacks(/var/tmp/xroad/jetty-proxy-ui-temp/webapp/WEB-INF/gems/gems/activesupport-3.2.22/lib/active_support/callbacks.rb:441)
    at RUBY._conditional_callback_around_98(/var/tmp/xroad/jetty-proxy-ui-temp/webapp/WEB-INF/gems/gems/activesupport-3.2.22/lib/active_support/callbacks.rb:225)
    at RUBY.translate_coded_exception(/var/tmp/xroad/jetty-proxy-ui-temp/webapp/WEB-INF/vendor/engines/common-ui/app/controllers/base_controller.rb:208)
    at RUBY._conditional_callback_around_98(/var/tmp/xroad/jetty-proxy-ui-temp/webapp/WEB-INF/gems/gems/activesupport-3.2.22/lib/active_support/callbacks.rb:224)
    at RUBY._run__224140107__process_action__1989452405__callbacks(/var/tmp/xroad/jetty-proxy-ui-temp/webapp/WEB-INF/gems/gems/activesupport-3.2.22/lib/active_support/callbacks.rb:429)
    at RUBY._conditional_callback_around_97(/var/tmp/xroad/jetty-proxy-ui-temp/webapp/WEB-INF/gems/gems/activesupport-3.2.22/lib/active_support/callbacks.rb:225)
    at RUBY.catch_java_exceptions(/var/tmp/xroad/jetty-proxy-ui-temp/webapp/WEB-INF/vendor/engines/common-ui/app/controllers/base_controller.rb:202)
    at RUBY._conditional_callback_around_97(/var/tmp/xroad/jetty-proxy-ui-temp/webapp/WEB-INF/gems/gems/activesupport-3.2.22/lib/active_support/callbacks.rb:224)
    at RUBY._run__224140107__process_action__1989452405__callbacks(/var/tmp/xroad/jetty-proxy-ui-temp/webapp/WEB-INF/gems/gems/activesupport-3.2.22/lib/active_support/callbacks.rb:428)
    at RUBY.__run_callback(/var/tmp/xroad/jetty-proxy-ui-temp/webapp/WEB-INF/gems/gems/activesupport-3.2.22/lib/active_support/callbacks.rb:405)
    at RUBY._run_process_action_callbacks(/var/tmp/xroad/jetty-proxy-ui-temp/webapp/WEB-INF/gems/gems/activesupport-3.2.22/lib/active_support/callbacks.rb:390)
    at RUBY.run_callbacks(/var/tmp/xroad/jetty-proxy-ui-temp/webapp/WEB-INF/gems/gems/activesupport-3.2.22/lib/active_support/callbacks.rb:81)
    at RUBY.process_action(/var/tmp/xroad/jetty-proxy-ui-temp/webapp/WEB-INF/gems/gems/actionpack-3.2.22/lib/abstract_controller/callbacks.rb:17)
    at RUBY.process_action(/var/tmp/xroad/jetty-proxy-ui-temp/webapp/WEB-INF/gems/gems/actionpack-3.2.22/lib/action_controller/metal/rescue.rb:29)
    at RUBY.process_action(/var/tmp/xroad/jetty-proxy-ui-temp/webapp/WEB-INF/gems/gems/actionpack-3.2.22/lib/action_controller/metal/instrumentation.rb:30)
    at RUBY.instrument(/var/tmp/xroad/jetty-proxy-ui-temp/webapp/WEB-INF/gems/gems/activesupport-3.2.22/lib/active_support/notifications.rb:123)
    at RUBY.instrument(/var/tmp/xroad/jetty-proxy-ui-temp/webapp/WEB-INF/gems/gems/activesupport-3.2.22/lib/active_support/notifications/instrumenter.rb:20)
    at RUBY.instrument(/var/tmp/xroad/jetty-proxy-ui-temp/webapp/WEB-INF/gems/gems/activesupport-3.2.22/lib/active_support/notifications.rb:123)
    at RUBY.process_action(/var/tmp/xroad/jetty-proxy-ui-temp/webapp/WEB-INF/gems/gems/actionpack-3.2.22/lib/action_controller/metal/instrumentation.rb:29)
    at RUBY.process_action(/var/tmp/xroad/jetty-proxy-ui-temp/webapp/WEB-INF/gems/gems/actionpack-3.2.22/lib/action_controller/metal/params_wrapper.rb:207)
    at RUBY.process(/var/tmp/xroad/jetty-proxy-ui-temp/webapp/WEB-INF/gems/gems/actionpack-3.2.22/lib/abstract_controller/base.rb:121)
    at RUBY.process(/var/tmp/xroad/jetty-proxy-ui-temp/webapp/WEB-INF/gems/gems/actionpack-3.2.22/lib/abstract_controller/rendering.rb:45)
    at RUBY.dispatch(/var/tmp/xroad/jetty-proxy-ui-temp/webapp/WEB-INF/gems/gems/actionpack-3.2.22/lib/action_controller/metal.rb:203)
    at RUBY.dispatch(/var/tmp/xroad/jetty-proxy-ui-temp/webapp/WEB-INF/gems/gems/actionpack-3.2.22/lib/action_controller/metal/rack_delegation.rb:14)
    at RUBY.action(/var/tmp/xroad/jetty-proxy-ui-temp/webapp/WEB-INF/gems/gems/actionpack-3.2.22/lib/action_controller/metal.rb:246)
    at org.jruby.RubyProc.call(org/jruby/RubyProc.java:271)
    at RUBY.dispatch(/var/tmp/xroad/jetty-proxy-ui-temp/webapp/WEB-INF/gems/gems/actionpack-3.2.22/lib/action_dispatch/routing/route_set.rb:73)
    at RUBY.call(/var/tmp/xroad/jetty-proxy-ui-temp/webapp/WEB-INF/gems/gems/actionpack-3.2.22/lib/action_dispatch/routing/route_set.rb:36)
    at RUBY.call(/var/tmp/xroad/jetty-proxy-ui-temp/webapp/WEB-INF/gems/gems/journey-1.0.4/lib/journey/router.rb:68)
    at org.jruby.RubyArray.each(org/jruby/RubyArray.java:1613)
    at RUBY.call(/var/tmp/xroad/jetty-proxy-ui-temp/webapp/WEB-INF/gems/gems/journey-1.0.4/lib/journey/router.rb:56)
    at RUBY.call(/var/tmp/xroad/jetty-proxy-ui-temp/webapp/WEB-INF/gems/gems/actionpack-3.2.22/lib/action_dispatch/routing/route_set.rb:608)
    at RUBY.call(/var/tmp/xroad/jetty-proxy-ui-temp/webapp/WEB-INF/gems/gems/actionpack-3.2.22/lib/action_dispatch/middleware/static.rb:83)
    at RUBY.call(/var/tmp/xroad/jetty-proxy-ui-temp/webapp/WEB-INF/gems/gems/actionpack-3.2.22/lib/action_dispatch/middleware/best_standards_support.rb:17)
    at RUBY.call(/var/tmp/xroad/jetty-proxy-ui-temp/webapp/WEB-INF/gems/gems/rack-1.4.7/lib/rack/etag.rb:23)
    at RUBY.call(/var/tmp/xroad/jetty-proxy-ui-temp/webapp/WEB-INF/gems/gems/rack-1.4.7/lib/rack/conditionalget.rb:25)
    at RUBY.call(/var/tmp/xroad/jetty-proxy-ui-temp/webapp/WEB-INF/gems/gems/actionpack-3.2.22/lib/action_dispatch/middleware/head.rb:14)
    at RUBY.call(/var/tmp/xroad/jetty-proxy-ui-temp/webapp/WEB-INF/gems/gems/actionpack-3.2.22/lib/action_dispatch/middleware/params_parser.rb:21)
    at RUBY.call(/var/tmp/xroad/jetty-proxy-ui-temp/webapp/WEB-INF/gems/gems/actionpack-3.2.22/lib/action_dispatch/middleware/flash.rb:242)
    at RUBY.context(file:/var/tmp/xroad/jetty-proxy-ui-temp/webapp/WEB-INF/lib/jruby-rack-1.1.19.jar!/jruby/rack/session_store.rb:79)
    at RUBY.call(/var/tmp/xroad/jetty-proxy-ui-temp/webapp/WEB-INF/gems/gems/rack-1.4.7/lib/rack/session/abstract/id.rb:205)
    at RUBY.call(/var/tmp/xroad/jetty-proxy-ui-temp/webapp/WEB-INF/gems/gems/actionpack-3.2.22/lib/action_dispatch/middleware/cookies.rb:341)
    at RUBY.call(/var/tmp/xroad/jetty-proxy-ui-temp/webapp/WEB-INF/gems/gems/actionpack-3.2.22/lib/action_dispatch/middleware/callbacks.rb:28)
    at RUBY._run__1561500324__call__1551446957__callbacks(/var/tmp/xroad/jetty-proxy-ui-temp/webapp/WEB-INF/gems/gems/activesupport-3.2.22/lib/active_support/callbacks.rb:408)
    at RUBY.__run_callback(/var/tmp/xroad/jetty-proxy-ui-temp/webapp/WEB-INF/gems/gems/activesupport-3.2.22/lib/active_support/callbacks.rb:405)
    at RUBY._run_call_callbacks(/var/tmp/xroad/jetty-proxy-ui-temp/webapp/WEB-INF/gems/gems/activesupport-3.2.22/lib/active_support/callbacks.rb:390)
    at RUBY.run_callbacks(/var/tmp/xroad/jetty-proxy-ui-temp/webapp/WEB-INF/gems/gems/activesupport-3.2.22/lib/active_support/callbacks.rb:81)
    at RUBY.call(/var/tmp/xroad/jetty-proxy-ui-temp/webapp/WEB-INF/gems/gems/actionpack-3.2.22/lib/action_dispatch/middleware/callbacks.rb:27)
    at RUBY.call(/var/tmp/xroad/jetty-proxy-ui-temp/webapp/WEB-INF/gems/gems/actionpack-3.2.22/lib/action_dispatch/middleware/remote_ip.rb:31)
    at RUBY.call(/var/tmp/xroad/jetty-proxy-ui-temp/webapp/WEB-INF/gems/gems/actionpack-3.2.22/lib/action_dispatch/middleware/debug_exceptions.rb:16)
    at RUBY.call(/var/tmp/xroad/jetty-proxy-ui-temp/webapp/WEB-INF/gems/gems/actionpack-3.2.22/lib/action_dispatch/middleware/show_exceptions.rb:56)
    at RUBY.call_app(/var/tmp/xroad/jetty-proxy-ui-temp/webapp/WEB-INF/gems/gems/railties-3.2.22/lib/rails/rack/logger.rb:32)
    at RUBY.call(/var/tmp/xroad/jetty-proxy-ui-temp/webapp/WEB-INF/gems/gems/railties-3.2.22/lib/rails/rack/logger.rb:16)
    at RUBY.tagged(/var/tmp/xroad/jetty-proxy-ui-temp/webapp/WEB-INF/gems/gems/activesupport-3.2.22/lib/active_support/tagged_logging.rb:22)
    at RUBY.call(/var/tmp/xroad/jetty-proxy-ui-temp/webapp/WEB-INF/gems/gems/railties-3.2.22/lib/rails/rack/logger.rb:16)
    at RUBY.call(/var/tmp/xroad/jetty-proxy-ui-temp/webapp/WEB-INF/gems/gems/actionpack-3.2.22/lib/action_dispatch/middleware/request_id.rb:22)
    at RUBY.call(/var/tmp/xroad/jetty-proxy-ui-temp/webapp/WEB-INF/gems/gems/rack-1.4.7/lib/rack/methodoverride.rb:21)
    at RUBY.call(/var/tmp/xroad/jetty-proxy-ui-temp/webapp/WEB-INF/gems/gems/rack-1.4.7/lib/rack/runtime.rb:17)
    at RUBY.call(/var/tmp/xroad/jetty-proxy-ui-temp/webapp/WEB-INF/gems/gems/activesupport-3.2.22/lib/active_support/cache/strategy/local_cache.rb:72)
    at RUBY.forward(/var/tmp/xroad/jetty-proxy-ui-temp/webapp/WEB-INF/gems/gems/rack-cache-1.2/lib/rack/cache/context.rb:136)
    at RUBY.fetch(/var/tmp/xroad/jetty-proxy-ui-temp/webapp/WEB-INF/gems/gems/rack-cache-1.2/lib/rack/cache/context.rb:245)
    at RUBY.lookup(/var/tmp/xroad/jetty-proxy-ui-temp/webapp/WEB-INF/gems/gems/rack-cache-1.2/lib/rack/cache/context.rb:185)
    at RUBY.call!(/var/tmp/xroad/jetty-proxy-ui-temp/webapp/WEB-INF/gems/gems/rack-cache-1.2/lib/rack/cache/context.rb:66)
    at RUBY.call(/var/tmp/xroad/jetty-proxy-ui-temp/webapp/WEB-INF/gems/gems/rack-cache-1.2/lib/rack/cache/context.rb:51)
    at RUBY.call(/var/tmp/xroad/jetty-proxy-ui-temp/webapp/WEB-INF/gems/gems/railties-3.2.22/lib/rails/engine.rb:484)
    at RUBY.call(/var/tmp/xroad/jetty-proxy-ui-temp/webapp/WEB-INF/gems/gems/railties-3.2.22/lib/rails/application.rb:231)
    at RUBY.call(file:/var/tmp/xroad/jetty-proxy-ui-temp/webapp/WEB-INF/lib/jruby-rack-1.1.19.jar!/rack/handler/servlet.rb:22)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(org/eclipse/jetty/servlet/ServletHandler.java:1667)
    at ee.ria.xroad.commonui.SessionTimeoutFilter.doFilter(ee/ria/xroad/commonui/SessionTimeoutFilter.java:108)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(org/eclipse/jetty/servlet/ServletHandler.java:1667)
    at ee.ria.xroad.commonui.jaas.AuthFilter.doFilter(ee/ria/xroad/commonui/jaas/AuthFilter.java:73)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(org/eclipse/jetty/servlet/ServletHandler.java:1667)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(org/eclipse/jetty/servlet/ServletHandler.java:581) 
```

**Comment by hvainsalu** [comment]
If the root cause has been discovered, the possible solution should be added to backlog for approval.

**Comment by hanhaka** [comment]
Fixed in 6.13.0

**Comment by lauri-aloauri** [comment]
Same thing happens in x-tee v6 t Security Server version 6.8.6.20161020095957 (ubuntu) which 40 -50 private keys. This happened suddenly. After that whrere is impossible to generate new keys, generatre certifiacte requests, import certifiactes. x-road securty server is after that unusable for key and certifiacte managment.

**Comment by lauri-aloauri** [comment]
The side effect thus major bug is  that all other operation after that more than sluggish. This makes administration of x-road security  server  more than fruitless effort.

**Comment by hanhaka** [comment]
Security Server (versions 6.7.x - v.6.9.x) should be able to handle ~200 keys based on our regression tests. However the limit depends on the size of keys in use. To the upcoming/next X-Road version (version 6.16.x) the limit has been doubled so that Security Server is able to handle ~400 keys.

**Comment by lauri-aloauri** [comment]
x-road v6 6.8.6.20161020095957 security server is not able to handle 40 -50 private keys. In Estonia is version 6.8.6 the official version. The sigener service is giving timeout messages. This bug is confirmed by help@ria.ee. We not able to generate eny new keys , certificate requests, import certificates. We even experimented with the signer-console but result is same. Under the signer-console we got following error messages:

list-tokens
HttpError: Connection to Signer (port 5558) timed out
HttpError: Connection to Signer (port 5558) timed out
        at ee.ria.xroad.signer.protocol.SignerClient.connectionTimeoutException(SignerClient.java:135)
        at ee.ria.xroad.signer.protocol.SignerClient.execute(SignerClient.java:100)
        at ee.ria.xroad.signer.console.SignerCLI.listTokens(SignerCLI.java:169)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at asg.cliche.ShellCommand.invoke(ShellCommand.java:69)
        at asg.cliche.Shell.processCommand(Shell.java:294)
        at asg.cliche.Shell.processLine(Shell.java:276)
        at asg.cliche.Shell.commandLoop(Shell.java:231)
        at ee.ria.xroad.signer.console.SignerCLI.startCommandLoop(SignerCLI.java:865)
        at ee.ria.xroad.signer.console.SignerCLI.main(SignerCLI.java:850)


list-keys
HttpError: Connection to Signer (port 5558) timed out
HttpError: Connection to Signer (port 5558) timed out
        at ee.ria.xroad.signer.protocol.SignerClient.connectionTimeoutException(SignerClient.java:135)
        at ee.ria.xroad.signer.protocol.SignerClient.execute(SignerClient.java:100)
        at ee.ria.xroad.signer.console.SignerCLI.listKeys(SignerCLI.java:179)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at asg.cliche.ShellCommand.invoke(ShellCommand.java:69)
        at asg.cliche.Shell.processCommand(Shell.java:294)

This bug very unpleasent and potentially very costly for us -  because our production x-road v6 security server clients  already have bought certifictes and we are not able to import them to production x-road v6 security server. Many of the  clients (40 -50 ) has already  bought 150 eur certificate

**Comment by jhyoty** [comment]
There is a workaround, try adding the following lines to /etc/xroad/services/local.conf (and restart the services):
```
PROXY_PARAMS="$PROXY_PARAMS -Dproxy.akka.remote.netty.tcp.maximum-frame-size=256k "
SIGNER_PARAMS="$SIGNER_PARAMS -Dsigner-main.akka.remote.netty.tcp.maximum-frame-size=256k "
SIGNER_CONSOLE_PARAMS="$SIGNER_CONSOLE_PARAMS -Dsigner-console.akka.remote.netty.tcp.maximum-frame-size=256k "
JETTY_PARAMS="$JETTY_PARAMS -Dproxyui.akka.remote.netty.tcp.maximum-frame-size=256k "
```

**Comment by lauri-aloauri** [comment]
Many thanks for  jhyoty . This workaround worked.
